Version 4
SymbolType BLOCK
RECTANGLE Normal 48 48 -48 -48
TEXT -48 -1 Left 0 PZTtrans
SYMATTR Value PZTtrans
SYMATTR Prefix X
SYMATTR SpiceModel PZTtrans.lib
SYMATTR Value2 PZTtrans
PIN -48 -32 LEFT 8
PINATTR PinName E
PINATTR SpiceOrder 1
PIN -48 32 LEFT 8
PINATTR PinName B
PINATTR SpiceOrder 2
PIN 48 32 RIGHT 8
PINATTR PinName F
PINATTR SpiceOrder 3
