Version 4
SymbolType BLOCK
RECTANGLE Normal -96 -64 96 64
PIN -96 0 LEFT 8
PINATTR PinName Mod_in
PINATTR SpiceOrder 1
PIN 0 -64 TOP 8
PINATTR PinName Vcc
PINATTR SpiceOrder 2
PIN 0 64 BOTTOM 8
PINATTR PinName Vss
PINATTR SpiceOrder 3
PIN 96 0 RIGHT 8
PINATTR PinName FmOut
PINATTR SpiceOrder 4
