Version 4
SymbolType BLOCK
RECTANGLE Normal 48 48 -48 -48
TEXT -28 -1 Left 0 PZT
SYMATTR Value PZT
SYMATTR Prefix X
SYMATTR SpiceModel PZT.lib
SYMATTR Value2 PZT
PIN -48 -32 LEFT 8
PINATTR PinName E
PINATTR SpiceOrder 1
PIN -48 32 LEFT 8
PINATTR PinName B
PINATTR SpiceOrder 2
PIN 48 32 RIGHT 8
PINATTR PinName F
PINATTR SpiceOrder 3
