Version 4
SymbolType CELL
RECTANGLE Normal 64 64 -64 -64
SYMATTR Prefix X
SYMATTR SpiceModel VPVCO
SYMATTR ModelFile VcoProg.sub
PIN -64 -48 LEFT 8
PINATTR PinName In
PINATTR SpiceOrder 1
PIN 64 0 RIGHT 8
PINATTR PinName Out
PINATTR SpiceOrder 2
PIN -64 -16 LEFT 8
PINATTR PinName Xdot
PINATTR SpiceOrder 3
PIN -64 16 LEFT 8
PINATTR PinName Ks
PINATTR SpiceOrder 4
PIN -64 48 LEFT 8
PINATTR PinName A
PINATTR SpiceOrder 5
PIN 0 64 BOTTOM 8
PINATTR PinName F0
PINATTR SpiceOrder 6
