Version 4
SymbolType CELL
RECTANGLE Normal 64 64 -80 -96
SYMATTR Prefix x
SYMATTR SpiceModel mlt04
SYMATTR ModelFile mult04.lib
PIN -80 -48 LEFT 8
PINATTR PinName X
PINATTR SpiceOrder 1
PIN -80 -16 LEFT 8
PINATTR PinName Y
PINATTR SpiceOrder 2
PIN -80 16 LEFT 8
PINATTR PinName gnd
PINATTR SpiceOrder 3
PIN 64 -16 RIGHT 8
PINATTR PinName W-out
PINATTR SpiceOrder 4
PIN 0 -96 TOP 8
PINATTR PinName Vcc
PINATTR SpiceOrder 5
PIN 0 64 BOTTOM 8
PINATTR PinName vss
PINATTR SpiceOrder 6
