Version 4
SymbolType CELL
RECTANGLE Normal -80 80 48 -96
TEXT -13 -85 Center 0 ANALsin
WINDOW 39 62 72 Left 0
SYMATTR SpiceLine Npp={Npp}
SYMATTR Description 3Phase Analog Sine Control
SYMATTR ModelFile BLDCSupport.lib
SYMATTR Prefix X
SYMATTR SpiceLine2 Dev=90 Offs=1.07
SYMATTR Value 3fcsin
PIN 48 -48 RIGHT 8
PINATTR PinName A
PINATTR SpiceOrder 1
PIN 48 0 RIGHT 8
PINATTR PinName B
PINATTR SpiceOrder 2
PIN 48 48 RIGHT 8
PINATTR PinName C
PINATTR SpiceOrder 3
PIN -80 48 LEFT 8
PINATTR PinName Dir
PINATTR SpiceOrder 4
PIN -80 -48 LEFT 8
PINATTR PinName M
PINATTR SpiceOrder 5
PIN -16 80 VLEFT 8
PINATTR PinName Angle
PINATTR SpiceOrder 6
