Version 4
SymbolType BLOCK
RECTANGLE Normal 128 42 -128 -57
TEXT -81 -8 Left 0 SQUID PARAM
SYMATTR Description Mammalian Neuron Nernst Potentials
PIN -80 48 BOTTOM 8
PINATTR PinName EK
PINATTR SpiceOrder 1
PIN 80 48 BOTTOM 8
PINATTR PinName ECl
PINATTR SpiceOrder 2
PIN 0 48 BOTTOM 8
PINATTR PinName ENa
PINATTR SpiceOrder 3
PIN -80 -64 TOP 8
PINATTR PinName KOut
PINATTR SpiceOrder 4
PIN 80 -64 TOP 8
PINATTR PinName ClOut
PINATTR SpiceOrder 5
PIN 0 -64 TOP 8
PINATTR PinName NaOut
PINATTR SpiceOrder 6
