Version 4
SymbolType CELL
RECTANGLE Normal 0 64 -32 -16
SYMATTR Prefix X
SYMATTR ModelFile Core.lib
SYMATTR Value2 Area=24u Len=32m
SYMATTR SpiceModel CoreSquare1
SYMATTR SpiceLine Hc=15 Br={0.6*0.96} BS=0.6
SYMATTR Description BAD MODEL
PIN -16 -16 NONE 8
PINATTR PinName IN
PINATTR SpiceOrder 1
PIN -16 64 NONE 8
PINATTR PinName OUT
PINATTR SpiceOrder 2
PIN 32 0 RIGHT 8
PINATTR PinName H
PINATTR SpiceOrder 3
PIN 32 48 RIGHT 8
PINATTR PinName B
PINATTR SpiceOrder 4
