Version 4
SymbolType BLOCK
RECTANGLE Normal 64 48 -80 -48
TEXT -87 65 Left 0 ONLY_BV&SH
WINDOW 0 -5 -55 Bottom 0
SYMATTR Description THE ERROR DIFFUSION ALGORITM USED AS PULSE DENSITY MODULATION ALGO
PIN -80 -32 LEFT 8
PINATTR PinName Sig
PINATTR SpiceOrder 1
PIN -80 32 LEFT 8
PINATTR PinName Start
PINATTR SpiceOrder 2
PIN 64 0 RIGHT 8
PINATTR PinName PDM
PINATTR SpiceOrder 3
